name: Get Raw Git Diff and Write to File

on:
  pull_request: # or push, depending on when you need this

jobs:
  get_diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history (important for diffing)

      - name: Debug Environment ONE
        run: |
          echo "Initial checkout branch name: `git rev-parse --abbrev-ref HEAD`"
          env

      - name: Checkout Main Branch
        run: git checkout ${GITHUB_BASE_REF} || git checkout main || git checkout master
        shell: bash

      - name: Debug Environment TWO
        run: |
          echo "Initial checkout branch name: `git rev-parse --abbrev-ref HEAD`"
          env

      # -- name: Dump Environment
      #   run: sh bin/actions/dump_env.sh

      -- name: Dump Environment
        run: |
          sh bin/actions/dump_env.sh

      - name: Get Feature Branch Name
        id: get-feature-branch
        run: |
          echo "FEATURE_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Check out Feature Branch
        run: git checkout ${{ steps.get-feature-branch.outputs.FEATURE_BRANCH }}

      - name: Get Raw Diff and Write to File
        run: |
          DIFF=$(git diff --raw main...${{ steps.get-feature-branch.outputs.FEATURE_BRANCH }})
          echo "$DIFF" > raw_diff.txt

      - name: Output Diff (Example - Read from File)
        run: |
          echo "Raw Diff (from file):"
          cat raw_diff.txt
